{% set version = "0.7.6" %}

package:
  name: pygpu
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/releases/download/v{{ version }}/libgpuarray-{{ version }}.tar.gz
  sha256: 887b6433a30282cb002117da89b05812c770fd9469f93950ff3866ddd02bfc64

build:
  number: 0
  script:
    - export CFLAGS="${CFLAGS} -I${PREFIX}/include -L${PREFIX}/lib"  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - cython >=0.25
    - numpy 1.11.*
    - mako
    - setuptools
    - libgpuarray =={{ version }}

  build:
    - {{ compiler('c') }}

  run:
    - python
    - numpy >=1.11
    - mako
    - six
    - libgpuarray =={{ version }}

test:
  imports:
    - pygpu
    - pygpu.gpuarray

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray

extra:
  recipe-maintainers:
    - abergeron
