travis:
  secure:
    BINSTAR_TOKEN: zM8TPuJ4PZWH2eDOzLYow01mVFDj8QWSgUD0pBfdaF3YRyaAzmoqw3NZYToaJQx9Q4LMhHDrUYxdTlFzFqLtHGOoF64/m2Me4eKF5hZiuTaIA5al1gM9tQKkwktCBRxK4CuNcPiRP2FY9x7xiVUhDCuzZzTCgLNeXCpPRLoYb5kGL0TmPPlHrJsT5bpAhdvR8PCN1KfHvnRKTxIR8cx5kWS4y6U1X3A6bvqgGWlkeD2ooCCFsDeKlnt4B56uxG5d7Fln9m0DL3OvCY1jXM6930Fipu9/fK5UpmkuDGg2dawrKLTt5fxa8byIK6MTJU+QfHBIMKyNdQDs5//4pgDXmoXWhShdyE28jnI5D7L2a/yHiR4PAGbmsJWllauDCYrCL9kVuhCLtnY872ykYB+FqWA700+1fPQmuRKV9OY9Ah3eY5wBAJ/1twwz4B/f5tsFo5lk9og0xjopQSivSH/no+jfoeIznjWUEpDuqJpiu92i4aNeDRSlCckg/3ZK3HkcPLAM6oIIWIhN9hOZMk7gDut7hUYZ9FxK0tioNIYIdSlOY2koFJ1OOCUm/rg75s1C2bfFD894L9nn/Jaofnqu+G/7wZO/8ISo3BGnI1bTDgm33KmE3pJSD//OlhQcSBwA6HxJVfkPCHyz/FrKMCcof3M264Y/1nmKXi2+kVuyxSU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
