travis:
  secure:
    BINSTAR_TOKEN: ezcPcHgcpiebAC7HbySE5ItlD0Da9qTitGqV1uwUXPu8KpS0Yktkquk/45mUbQKLC2+RlROS3XA43eRvr9j0NXFP0be1xlHJlMfC832UzFAEMGvbXjkd1bKsqmE9GQBMpjyLaxzZvXuRxpCvnJ8oRESRTSl6aZbFnJsvbVMMAVH2U8XLaMD/9IFd3qmiXZnKyUkjmtc0A7KftQ7Xk32Wr2RhB4zqvT6SHSzYZ1uKIWNN6mN1G+pe3zrIdY/B5SflWFoetU2GboUtGCffANFupLKkftXA9ky4UlsIjO6o8i6ndWIzdyXJYcAWJ5FNvF+EN8OVrhrf6q1f/cdFAVYry/+TtJX4yXbzCqaLLCBSsYhxMBjq9X5qcqQd0RWKchkuScVEyQkk10ucaqi/boCVi//ZP+9+vA9GNHDvot7t4QcCBgrbU40jZLEuKieTaEKoe3CNS4UFzfDrXtMzlAJwjoMPnbmf5Uo2hJAcmQR6LfgteUvvFUJuZ1/jJm6VLKiOGaq7RE+eqN1D8XENdbpmRmM46hguq30PkcCCvfcn8S3XE9uAqCZd7YZ6kdkOv+pLFr7rqT3es6jWGCT9Kfst1ja6g+oKOpnWO7TYneGgzWRTZ2+9eIjKEfwAEQER+xEw5eXR+k5JWVIMQNEFaE8cCqsuGFXKYoEl9WdceRpueSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
